#!/usr/bin/env python

import subprocess
import sys


CRED = '\033[91m'
CEND = '\033[0m'

UNCHANGED_ENCRYPTION_KEY = 'YOUR_ENCRYPTED_KEY'

URL_ENCRYPTION_KEY = 'https://api.speedtracker.org/encrypt/{key}/'
WGET_CMD = 'wget --no-verbose --timeout 5 -O - {url}'


def version_check():
	if sys.version_info < (2, 7):
		raise Exception('Must use python 2.7 or greater')


def run_cmd(cmd):
	p = subprocess.Popen(
			cmd.split(' '), 
			stdout=subprocess.PIPE,
			stderr=subprocess.PIPE,
		)

	out, err = p.communicate()
	
	if p.returncode == 0:
		return out

	raise Exception('Failed making a call to {cmd}: {err}'.format(
		cmd=cmd,
		err=err,
	))


def make_call(url):
	cmd = WGET_CMD.format(url=url)

	return run_cmd(cmd)


def setup_encryption_key():
	key = ''
	while key == '':
		key = raw_input('Enter your encryption key: ')

	url = URL_ENCRYPTION_KEY.format(key=key)
	encryption_key = make_call(url)

	print encryption_key


def main():
	print '----Speedtracker setup----'
	try:
		version_check()
		setup_encryption_key()
	except Exception as e:
		print CRED + 'Error: {err}'.format(err=str(e)) + CEND


if __name__ == '__main__':
	main()